name: pr-labeler
on:
  pull_request:
    types: [opened, reopened]

jobs:
  add_milestone_from_issue:
    runs-on: ubuntu-latest
    steps:
    - uses: egorkqq/smart-labeler-action@main
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
